name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      OUTPUT_DIR: ./output

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Prepare Output Directory
      run: |
        if (!(Test-Path -Path $env:OUTPUT_DIR)) {
          New-Item -ItemType Directory -Path $env:OUTPUT_DIR
        }

    - name: Compile 64bit Binary
      run: |
        gcc .\src\main.c -o $env:OUTPUT_DIR\main.exe -s -m64

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binary
        path: ${{ env.OUTPUT_DIR }}/main.exe