name: Build and Publish Draft Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      OUTPUT_DIR: ./output

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Prepare Output Directory
      run: |
        if (!(Test-Path -Path $env:OUTPUT_DIR)) {
          New-Item -ItemType Directory -Path $env:OUTPUT_DIR
        }

    - name: Compile 64bit Binary
      run: |
        gcc .\src\main.c -o $env:OUTPUT_DIR\main.exe -s -m64

    - name: Create or Update Draft Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly
        name: Nightly Build
        draft: false
        prerelease: true
        files: ${{ env.OUTPUT_DIR }}/main.exe