name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    env:
      OUTPUT_DIR: ./output

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Prepare Output Directory
      run: |
        if (!(Test-Path -Path $env:OUTPUT_DIR)) {
          New-Item -ItemType Directory -Path $env:OUTPUT_DIR
        }

    - name: Compile 64bit Binary
      run: |
        gcc .\src\main.c -o $env:OUTPUT_DIR\main.exe -s -m64 -lntdll

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: ${{ env.OUTPUT_DIR }}/main.exe